### ad_clicks

In [1]:
import pandas as pd

In [2]:
ad_clicks = pd.read_csv('ad_clicks.csv')

1. Examine the first few rows of ad_clicks.

In [4]:
ad_clicks.head()

,user_id,utm_source,day,ad_click_timestamp,experimental_group
0,008b7c6c-7272-471e-b90e-930d548bd8d7,google,6 - Saturday,07:18,A
1,009abb94-5e14-4b6c-bb1c-4f4df7aa7557,facebook,7 - Sunday,NaN,B
2,00f5d532-ed58-4570-b6d2-768df5f41aed,twitter,2 - Tuesday,NaN,A
3,011adc64-0f44-4fd9-a0bb-f1506d2ad439,google,2 - Tuesday,NaN,B
4,012137e6-7ae7-4649-af68-205b4702169c,facebook,7 - Sunday,NaN,B

2.
Your manager wants to know which ad platform is getting you the most views.
How many views (i.e., rows of the table) came from each utm_source?

In [6]:
ad_clicks.groupby('utm_source').count()

            user_id  day  ad_click_timestamp  experimental_group
utm_source
email           255  255                  80                 255
facebook        504  504                 180                 504
google          680  680                 239                 680
twitter         215  215                  66                 215

3.
If the column ad_click_timestamp is not null, then someone actually clicked on the ad that was displayed.
Create a new column called is_click, which is True if ad_click_timestamp is not null and False otherwise.

In [10]:
ad_clicks['is_click'] = ~ad_clicks.ad_click_timestamp.isnull()
ad_clicks

,user_id,utm_source,day,ad_click_timestamp,experimental_group,is_click
0,008b7c6c-7272-471e-b90e-930d548bd8d7,google,6 - Saturday,07:18,A,True
1,009abb94-5e14-4b6c-bb1c-4f4df7aa7557,facebook,7 - Sunday,NaN,B,False
2,00f5d532-ed58-4570-b6d2-768df5f41aed,twitter,2 - Tuesday,NaN,A,False
3,011adc64-0f44-4fd9-a0bb-f1506d2ad439,google,2 - Tuesday,NaN,B,False
4,012137e6-7ae7-4649-af68-205b4702169c,facebook,7 - Sunday,NaN,B,False
5,013b0072-7b72-40e7-b698-98b4d0c9967f,facebook,1 - Monday,NaN,A,False
6,0153d85b-7660-4c39-92eb-1e1acd023280,google,4 - Thursday,NaN,A,False
7,01555297-d6e6-49ae-aeba-1b196fdbb09f,google,3 - Wednesday,NaN,A,False
8,018cea61-19ea-4119-895b-1a4309ccb148,email,1 - Monday,18:33,A,True
9,01a210c3-fde0-4e6f-8efd-4f0e38730ae6,email,2 - Tuesday,15:21,B,True
10,01adb2e7-f711-4ae4-a7c6-29f48457eea1,google,3 - Wednesday,NaN,B,False
11,01ae0361-7d17-4760-a2c8-23977a46fb78,facebook,4 - Thursday,07:11,B,True
12,01fb228a-9d28-4cde-932c-59b933fa763b,email,7 - Sunday,NaN,A,False
13,023598b8-09e2-40ed-9c90-34d607094ff9,google,2 - Tuesday,NaN,B,False
14,02405d93-9c33-4034-894a-b9523956a3ad,twitter,2 - Tuesday,NaN,A,False
15,0254b59f-082d-4a5a-913d-4f2bba267768,google,5 - Friday,NaN,A,False
16,02d8dba0-5d12-4983-a407-63fab9757d94,google,3 - Wednesday,NaN,B,False
17,0378e9e1-0ad8-4a26-8190-ebb3370239d3,facebook,1 - Monday,NaN,B,False
18,041deef8-b242-4114-afd0-e584784ec9f0,google,3 - Wednesday,10:54,A,True
19,0429608e-61f3-4df0-ba45-3633029a14db,google,7 - Sunday,NaN,B,False
20,04389894-b52c-4485-9266-435e9b9c0efd,email,1 - Monday,NaN,B,False
21,0441f866-dd3f-422a-a36a-cdc2f034e6ef,google,7 - Sunday,11:16,A,True
22,04797f05-9cbe-48b6-8662-b9ee20828b0a,google,6 - Saturday,NaN,B,False
23,0482e1ab-b513-4bfb-9914-9fb5ab41c915,twitter,6 - Saturday,01:20,A,True
24,04ca737b-85f4-4194-8c38-d8d363b490f7,google,2 - Tuesday,NaN,B,False
25,056f771f-e5ba-483f-a074-db2d7b94309d,google,4 - Thursday,NaN,A,False
26,05aec9ea-92c1-4ffc-84b5-c3864dd307e4,facebook,5 - Friday,08:46,B,True
27,05c41c49-8521-4ad0-a1b5-724e99fe46ff,facebook,7 - Sunday,NaN,B,False
28,05d08d6d-62d5-4e28-8f10-107ae2cd03c7,facebook,2 - Tuesday,NaN,A,False
29,05e8721a-cbb7-4c13-a115-eac7dd5ee7f6,email,5 - Friday,NaN,B,False
...,...,...,...,...,...,...
1624,fa90b2a6-1eb1-448e-b9ba-54ff5d442d49,google,4 - Thursday,04:40,B,True
1625,faa01b50-4b17-460a-9b8e-f3935cea6adc,twitter,2 - Tuesday,NaN,B,False
1626,fac695dc-d76c-4b98-a21c-57b7fbd16d68,twitter,3 - Wednesday,NaN,B,False
1627,facb25df-6e02-43c7-a15b-f959560ad03c,twitter,1 - Monday,NaN,A,False
1628,fb146d44-601c-4517-9baa-9330bfa88bba,facebook,7 - Sunday,02:56,B,True
1629,fb32740b-fabd-4003-81c6-7d2017b9eaa0,email,3 - Wednesday,13:12,A,True
1630,fb36e78d-6af7-444c-9fda-df7f8605396a,email,6 - Saturday,NaN,B,False
1631,fb6338a5-cc13-4015-8787-42cc141cf93f,email,1 - Monday,NaN,B,False
1632,fba790d4-a75a-4ffb-b680-f1a82004a034,twitter,2 - Tuesday,NaN,A,False
1633,fba8627b-cd53-4efe-a70c-e2020ccf6f8d,facebook,2 - Tuesday,11:23,B,True
1634,fbc58b4b-0282-4be9-8191-6197d0e6ab94,twitter,2 - Tuesday,NaN,A,False
1635,fbd906ae-678e-44e9-b687-53d228cd36ac,google,5 - Friday,NaN,A,False
1636,fbe94d97-d99b-4963-a60a-0218df925843,email,3 - Wednesday,NaN,A,False
1637,fc1f4540-550f-4900-bda7-88d3bbfc95e4,email,5 - Friday,NaN,B,False
1638,fc236775-0677-4432-a985-527638514f1f,google,4 - Thursday,NaN,B,False
1639,fc35290d-8402-449e-9324-79a1cbb80342,google,7 - Sunday,NaN,B,False
1640,fc6c286c-4562-45a7-be46-c24ad6d0b7a9,google,4 - Thursday,NaN,A,False
1641,fcc78eea-9bd0-4e42-b159-890ba62ff5c1,email,2 - Tuesday,NaN,B,False
1642,fce1eb2a-cf8b-4ec4-a2f7-2fe70d23775a,facebook,5 - Friday,NaN,A,False
1643,fceb13ea-fd8c-446a-a61f-f977d404330a,twitter,6 - Saturday,NaN,A,False
1644,fd0538d1-5871-4e88-942c-a094479a6ece,google,6 - Saturday,NaN,B,False
1645,fd2a5852-f0ef-4162-84a6-107a42dc46b5,twitter,3 - Wednesday,NaN,B,False
1646,fd7d06ea-38b5-4ed9-acc9-777047db8c56,google,4 - Thursday,NaN,A,False
1647,fe570a20-448f-40ed-930b-8482b8a7c231,facebook,1 - Monday,20:07,A,True
1648,fe6cfa5a-cc63-4770-8d56-c13ac8cf5bef,google,3 - Wednesday,15:06,B,True
1649,fe8b5236-78f6-4192-9da6-a76bba67cfe6,twitter,7 - Sunday,NaN,A,False
1650,fed3db6d-8c92-40e3-a4fb-1fb9d7337eb1,facebook,5 - Friday,NaN,B,False
1651,ff3a22ff-521c-478c-87ca-7dc7b8f34372,twitter,3 - Wednesday,NaN,B,False
1652,ff3af0d6-b092-4c4d-9f2e-2bdd8f7c0732,google,1 - Monday,22:57,A,True
1653,ffdfe7ec-0c74-4623-8d90-d95d80f1ba34,facebook,6 - Saturday,NaN,B,False

4.
We want to know the percent of people who clicked on ads from each utm_source.
Start by grouping by utm_source and is_click and counting the number of 
user_id‘s in each of those groups. Save your answer to the variable clicks_by_source.

In [11]:
clicks_by_source = ad_clicks.groupby(['utm_source', 'is_click']).count().reset_index()
clicks_by_source

  utm_source  is_click  user_id  day  ad_click_timestamp  experimental_group
0      email     False      175  175                   0                 175
1      email      True       80   80                  80                  80
2   facebook     False      324  324                   0                 324
3   facebook      True      180  180                 180                 180
4     google     False      441  441                   0                 441
5     google      True      239  239                 239                 239
6    twitter     False      149  149                   0                 149
7    twitter      True       66   66                  66                  66

5. Now let’s pivot the data so that the columns are is_click 
(either True or False), the index is utm_source, and the values are user_id.
Save your results to the variable clicks_pivot.

In [12]:
clicks_pivot = clicks_by_source\
   .pivot(index='utm_source',
          columns='is_click',
          values='user_id')\
   .reset_index()
clicks_pivot

is_click utm_source  False  True
0             email    175    80
1          facebook    324   180
2            google    441   239
3           twitter    149    66

6.
Create a new column in clicks_pivot called percent_clicked which is
 equal to the percent of users who clicked on the ad from each utm_source.
Was there a difference in click rates for each source?

In [13]:
clicks_pivot['percent_clicked'] = clicks_pivot[True] / (clicks_pivot[True] + clicks_pivot[False])
clicks_pivot

is_click utm_source  False  True  percent_clicked
0             email    175    80         0.313725
1          facebook    324   180         0.357143
2            google    441   239         0.351471
3           twitter    149    66         0.306977

7.
The column experimental_group tells us whether the user was shown Ad A or Ad B.
Were approximately the same number of people shown both adds?

In [14]:
ad_clicks.groupby('experimental_group').count()

                    user_id  utm_source  day  ad_click_timestamp  is_click
experimental_group
A                       827         827  827                 310       827
B                       827         827  827                 255       827

8.
Using the column is_click that we defined earlier, check to see 
if a greater percentage of users clicked on Ad A or Ad B.

In [24]:
ad_df = ad_clicks.groupby(['experimental_group', 'is_click']).user_id.count().reset_index()
ad_df

  experimental_group  is_click  user_id
0                  A     False      517
1                  A      True      310
2                  B     False      572
3                  B      True      255

In [25]:
ad_clicks_pivot = ad_df\
   .pivot(index='experimental_group',
          columns='is_click',
          values='user_id')\
   .reset_index()
ad_clicks_pivot

is_click experimental_group  False  True
0                         A    517   310
1                         B    572   255

In [27]:
ad_clicks_pivot['percent_clicked'] = ad_clicks_pivot[True] / (ad_clicks_pivot[True] + ad_clicks_pivot[False])
ad_clicks_pivot

is_click experimental_group  False  True  percent_clicked
0                         A    517   310         0.374849
1                         B    572   255         0.308343

9.
The Product Manager for the A/B test thinks that the clicks might have changed by day of the week.
Start by creating two DataFrames: a_clicks and b_clicks,
which contain only the results for A group and B group, respectively.

In [17]:
a_clicks = ad_clicks[ad_clicks.experimental_group == 'A' ]
a_clicks

,user_id,utm_source,day,ad_click_timestamp,experimental_group,is_click
0,008b7c6c-7272-471e-b90e-930d548bd8d7,google,6 - Saturday,07:18,A,True
2,00f5d532-ed58-4570-b6d2-768df5f41aed,twitter,2 - Tuesday,NaN,A,False
5,013b0072-7b72-40e7-b698-98b4d0c9967f,facebook,1 - Monday,NaN,A,False
6,0153d85b-7660-4c39-92eb-1e1acd023280,google,4 - Thursday,NaN,A,False
7,01555297-d6e6-49ae-aeba-1b196fdbb09f,google,3 - Wednesday,NaN,A,False
8,018cea61-19ea-4119-895b-1a4309ccb148,email,1 - Monday,18:33,A,True
12,01fb228a-9d28-4cde-932c-59b933fa763b,email,7 - Sunday,NaN,A,False
14,02405d93-9c33-4034-894a-b9523956a3ad,twitter,2 - Tuesday,NaN,A,False
15,0254b59f-082d-4a5a-913d-4f2bba267768,google,5 - Friday,NaN,A,False
18,041deef8-b242-4114-afd0-e584784ec9f0,google,3 - Wednesday,10:54,A,True
21,0441f866-dd3f-422a-a36a-cdc2f034e6ef,google,7 - Sunday,11:16,A,True
23,0482e1ab-b513-4bfb-9914-9fb5ab41c915,twitter,6 - Saturday,01:20,A,True
25,056f771f-e5ba-483f-a074-db2d7b94309d,google,4 - Thursday,NaN,A,False
28,05d08d6d-62d5-4e28-8f10-107ae2cd03c7,facebook,2 - Tuesday,NaN,A,False
30,06234d6f-8729-49d3-a39e-6bba740847e3,facebook,6 - Saturday,NaN,A,False
33,06a8681a-7de2-4053-8462-29df2b1e8aab,facebook,7 - Sunday,09:02,A,True
34,06aa1cc0-4366-4558-b74c-24bb797cff0b,email,4 - Thursday,NaN,A,False
38,076b9eb7-a7c3-4319-a830-eb3344d88b6e,google,5 - Friday,NaN,A,False
41,0789f648-70fa-4711-8d1c-62ddde084aff,google,1 - Monday,NaN,A,False
44,082ad0da-546b-4c00-b2f8-e21a5113e66a,facebook,2 - Tuesday,NaN,A,False
47,084e8dc0-94df-4321-bbde-dc521b5c58d9,facebook,2 - Tuesday,NaN,A,False
50,09347a02-3824-481b-a9aa-706047b3fcb0,facebook,4 - Thursday,16:52,A,True
53,0a046b08-1ed1-4ff6-b64c-176d1472dc9b,facebook,1 - Monday,NaN,A,False
56,0aa54825-7375-4b19-8622-d5e8ce41b73e,twitter,4 - Thursday,10:21,A,True
58,0b4a71b1-b264-4bc3-8ca3-d8c893e009ef,email,5 - Friday,NaN,A,False
60,0bece189-a24f-4dcf-888e-583381a26383,google,4 - Thursday,NaN,A,False
61,0bf24554-eac9-423d-8dc0-349e9629f422,facebook,1 - Monday,02:02,A,True
63,0c8fbfbf-38e6-4639-8aff-26f3dbd4492b,google,4 - Thursday,12:23,A,True
64,0cb5db50-1ded-4f68-8574-30b94677e4b8,facebook,2 - Tuesday,04:08,A,True
65,0d16721b-99cc-4fda-8285-dc0675b93c26,google,4 - Thursday,05:27,A,True
...,...,...,...,...,...,...
1589,f5e05a87-fa0f-4c79-a015-4aa97a2b4910,google,3 - Wednesday,NaN,A,False
1591,f613bbd9-e766-4084-92a2-cf45a8193229,twitter,5 - Friday,NaN,A,False
1597,f68e3599-66f9-4af0-bb3d-2f68591fed97,facebook,1 - Monday,15:39,A,True
1598,f69bcfa4-0f02-408f-a01d-bdb6cd985eff,google,7 - Sunday,NaN,A,False
1600,f6cfd4ae-bada-4580-b3ce-61d701ac5175,google,4 - Thursday,NaN,A,False
1602,f6fcb204-dd88-4797-9142-82aadd1f56af,facebook,4 - Thursday,NaN,A,False
1604,f7cf8d26-98cf-4bf0-a11e-a22b39df45cf,twitter,4 - Thursday,18:43,A,True
1605,f806511f-fda2-4d4f-b735-2b8e0fe3e671,google,3 - Wednesday,NaN,A,False
1606,f80758b2-4c0e-4e28-93cb-aa3b7e39a905,twitter,7 - Sunday,08:05,A,True
1607,f81f216a-1df1-49d1-b417-04b6c5f75510,facebook,2 - Tuesday,17:03,A,True
1609,f84f15db-bdaa-4024-8f6d-30a139a65dc9,facebook,3 - Wednesday,NaN,A,False
1610,f8822961-6bdf-4d4c-a27a-22ad30dbcf99,google,3 - Wednesday,20:50,A,True
1613,f8f8de19-1129-497b-a8fd-1f357bb103a0,facebook,6 - Saturday,11:06,A,True
1614,f8fb4bc7-b0b0-434f-8910-d9571b097d15,facebook,2 - Tuesday,07:44,A,True
1617,f97f3e9a-e469-4e0e-aeff-6d0da7bcc736,google,6 - Saturday,NaN,A,False
1618,f99f4cae-79cd-4a8d-8fff-bf3002a15cb5,google,5 - Friday,NaN,A,False
1621,f9f391d9-67d3-4672-bc9d-7da38306053e,twitter,5 - Friday,23:24,A,True
1627,facb25df-6e02-43c7-a15b-f959560ad03c,twitter,1 - Monday,NaN,A,False
1629,fb32740b-fabd-4003-81c6-7d2017b9eaa0,email,3 - Wednesday,13:12,A,True
1632,fba790d4-a75a-4ffb-b680-f1a82004a034,twitter,2 - Tuesday,NaN,A,False
1634,fbc58b4b-0282-4be9-8191-6197d0e6ab94,twitter,2 - Tuesday,NaN,A,False
1635,fbd906ae-678e-44e9-b687-53d228cd36ac,google,5 - Friday,NaN,A,False
1636,fbe94d97-d99b-4963-a60a-0218df925843,email,3 - Wednesday,NaN,A,False
1640,fc6c286c-4562-45a7-be46-c24ad6d0b7a9,google,4 - Thursday,NaN,A,False
1642,fce1eb2a-cf8b-4ec4-a2f7-2fe70d23775a,facebook,5 - Friday,NaN,A,False
1643,fceb13ea-fd8c-446a-a61f-f977d404330a,twitter,6 - Saturday,NaN,A,False
1646,fd7d06ea-38b5-4ed9-acc9-777047db8c56,google,4 - Thursday,NaN,A,False
1647,fe570a20-448f-40ed-930b-8482b8a7c231,facebook,1 - Monday,20:07,A,True
1649,fe8b5236-78f6-4192-9da6-a76bba67cfe6,twitter,7 - Sunday,NaN,A,False
1652,ff3af0d6-b092-4c4d-9f2e-2bdd8f7c0732,google,1 - Monday,22:57,A,True

In [18]:
b_clicks = ad_clicks[ad_clicks.experimental_group == 'B' ]
b_clicks

,user_id,utm_source,day,ad_click_timestamp,experimental_group,is_click
1,009abb94-5e14-4b6c-bb1c-4f4df7aa7557,facebook,7 - Sunday,NaN,B,False
3,011adc64-0f44-4fd9-a0bb-f1506d2ad439,google,2 - Tuesday,NaN,B,False
4,012137e6-7ae7-4649-af68-205b4702169c,facebook,7 - Sunday,NaN,B,False
9,01a210c3-fde0-4e6f-8efd-4f0e38730ae6,email,2 - Tuesday,15:21,B,True
10,01adb2e7-f711-4ae4-a7c6-29f48457eea1,google,3 - Wednesday,NaN,B,False
11,01ae0361-7d17-4760-a2c8-23977a46fb78,facebook,4 - Thursday,07:11,B,True
13,023598b8-09e2-40ed-9c90-34d607094ff9,google,2 - Tuesday,NaN,B,False
16,02d8dba0-5d12-4983-a407-63fab9757d94,google,3 - Wednesday,NaN,B,False
17,0378e9e1-0ad8-4a26-8190-ebb3370239d3,facebook,1 - Monday,NaN,B,False
19,0429608e-61f3-4df0-ba45-3633029a14db,google,7 - Sunday,NaN,B,False
20,04389894-b52c-4485-9266-435e9b9c0efd,email,1 - Monday,NaN,B,False
22,04797f05-9cbe-48b6-8662-b9ee20828b0a,google,6 - Saturday,NaN,B,False
24,04ca737b-85f4-4194-8c38-d8d363b490f7,google,2 - Tuesday,NaN,B,False
26,05aec9ea-92c1-4ffc-84b5-c3864dd307e4,facebook,5 - Friday,08:46,B,True
27,05c41c49-8521-4ad0-a1b5-724e99fe46ff,facebook,7 - Sunday,NaN,B,False
29,05e8721a-cbb7-4c13-a115-eac7dd5ee7f6,email,5 - Friday,NaN,B,False
31,068ad376-b5c2-4825-afc0-2be657e1f4df,email,3 - Wednesday,NaN,B,False
32,06a18971-a97b-48a4-bda6-3881960e3796,google,4 - Thursday,NaN,B,False
35,06cf79f4-ac53-4b72-8736-829b8c63c7df,google,6 - Saturday,NaN,B,False
36,06da5468-c366-4388-b0ac-f84ea36949e0,google,5 - Friday,NaN,B,False
37,07476cb4-247d-4fe2-b830-a399717bd07e,twitter,7 - Sunday,NaN,B,False
39,0771c92b-2ec8-463d-99fc-d4c31b7264b1,google,7 - Sunday,NaN,B,False
40,07760e06-0ff5-4f4b-a483-eaa46e504aca,email,3 - Wednesday,NaN,B,False
42,07cc1e2c-b5cc-4daf-95f2-2326021e7d52,google,4 - Thursday,NaN,B,False
43,081372d5-a1a8-4819-9bf1-911d4855360c,twitter,7 - Sunday,NaN,B,False
45,083e3bbf-abe4-418c-8b17-7ac77b436ab1,google,2 - Tuesday,03:21,B,True
46,0846d988-4b9e-4593-857b-594dabb8d5bb,google,4 - Thursday,NaN,B,False
48,089cd63a-f7e2-4381-a864-b4378334885f,facebook,7 - Sunday,NaN,B,False
49,0928d4d2-9012-4806-99f7-06672ede99af,google,3 - Wednesday,NaN,B,False
51,097b056d-bad3-4fd0-a304-2c1a74bfc64e,google,1 - Monday,NaN,B,False
...,...,...,...,...,...,...
1596,f68d7a03-85cd-4e6e-bb91-07ad67509345,google,6 - Saturday,NaN,B,False
1599,f6a4a025-8a7c-4a0b-8c74-28e7fc5349b1,facebook,3 - Wednesday,NaN,B,False
1601,f6e95a56-73bb-4dc6-8671-4b051eb3d050,google,3 - Wednesday,06:48,B,True
1603,f7853567-44db-409f-827c-d4114394e434,facebook,1 - Monday,07:30,B,True
1608,f840b38a-5476-4018-82bd-e3cea42ba664,facebook,2 - Tuesday,NaN,B,False
1611,f8a689db-26a6-4a33-b158-a5d64a34d0fe,email,2 - Tuesday,23:20,B,True
1612,f8c7f440-4b2c-4200-9136-a199cec125d3,twitter,4 - Thursday,10:32,B,True
1615,f9016121-4210-4163-971b-90a17a136d8d,email,4 - Thursday,NaN,B,False
1616,f91cdcfe-98fd-4a98-8d75-b358c839fda5,twitter,2 - Tuesday,05:54,B,True
1619,f9a96379-4b43-468c-98ad-2f5c8ef8b0d2,email,3 - Wednesday,NaN,B,False
1620,f9dc952e-4789-45f2-b739-5acfaef36dbd,twitter,1 - Monday,NaN,B,False
1622,fa2b3f35-19a7-4cf7-8c1f-69f0ec8910ea,twitter,4 - Thursday,NaN,B,False
1623,fa392e7c-3460-4292-addb-0fc096e90b7a,facebook,5 - Friday,23:33,B,True
1624,fa90b2a6-1eb1-448e-b9ba-54ff5d442d49,google,4 - Thursday,04:40,B,True
1625,faa01b50-4b17-460a-9b8e-f3935cea6adc,twitter,2 - Tuesday,NaN,B,False
1626,fac695dc-d76c-4b98-a21c-57b7fbd16d68,twitter,3 - Wednesday,NaN,B,False
1628,fb146d44-601c-4517-9baa-9330bfa88bba,facebook,7 - Sunday,02:56,B,True
1630,fb36e78d-6af7-444c-9fda-df7f8605396a,email,6 - Saturday,NaN,B,False
1631,fb6338a5-cc13-4015-8787-42cc141cf93f,email,1 - Monday,NaN,B,False
1633,fba8627b-cd53-4efe-a70c-e2020ccf6f8d,facebook,2 - Tuesday,11:23,B,True
1637,fc1f4540-550f-4900-bda7-88d3bbfc95e4,email,5 - Friday,NaN,B,False
1638,fc236775-0677-4432-a985-527638514f1f,google,4 - Thursday,NaN,B,False
1639,fc35290d-8402-449e-9324-79a1cbb80342,google,7 - Sunday,NaN,B,False
1641,fcc78eea-9bd0-4e42-b159-890ba62ff5c1,email,2 - Tuesday,NaN,B,False
1644,fd0538d1-5871-4e88-942c-a094479a6ece,google,6 - Saturday,NaN,B,False
1645,fd2a5852-f0ef-4162-84a6-107a42dc46b5,twitter,3 - Wednesday,NaN,B,False
1648,fe6cfa5a-cc63-4770-8d56-c13ac8cf5bef,google,3 - Wednesday,15:06,B,True
1650,fed3db6d-8c92-40e3-a4fb-1fb9d7337eb1,facebook,5 - Friday,NaN,B,False
1651,ff3a22ff-521c-478c-87ca-7dc7b8f34372,twitter,3 - Wednesday,NaN,B,False
1653,ffdfe7ec-0c74-4623-8d90-d95d80f1ba34,facebook,6 - Saturday,NaN,B,False

10.
For each group (a_clicks and b_clicks), calculate the percent of users who clicked on the ad by day.

In [37]:
a_clicks_grouped = a_clicks.groupby(['day', 'is_click']).count().reset_index()
a_clicks_grouped

,day,is_click,user_id,utm_source,ad_click_timestamp,experimental_group
0,1 - Monday,False,70,70,0,70
1,1 - Monday,True,43,43,43,43
2,2 - Tuesday,False,76,76,0,76
3,2 - Tuesday,True,43,43,43,43
4,3 - Wednesday,False,86,86,0,86
5,3 - Wednesday,True,38,38,38,38
6,4 - Thursday,False,69,69,0,69
7,4 - Thursday,True,47,47,47,47
8,5 - Friday,False,77,77,0,77
9,5 - Friday,True,51,51,51,51
10,6 - Saturday,False,73,73,0,73
11,6 - Saturday,True,45,45,45,45
12,7 - Sunday,False,66,66,0,66
13,7 - Sunday,True,43,43,43,43

In [39]:
b_clicks_grouped = b_clicks.groupby(['day', 'is_click']).count().reset_index()
b_clicks_grouped

,day,is_click,user_id,utm_source,ad_click_timestamp,experimental_group
0,1 - Monday,False,81,81,0,81
1,1 - Monday,True,32,32,32,32
2,2 - Tuesday,False,74,74,0,74
3,2 - Tuesday,True,45,45,45,45
4,3 - Wednesday,False,89,89,0,89
5,3 - Wednesday,True,35,35,35,35
6,4 - Thursday,False,87,87,0,87
7,4 - Thursday,True,29,29,29,29
8,5 - Friday,False,90,90,0,90
9,5 - Friday,True,38,38,38,38
10,6 - Saturday,False,76,76,0,76
11,6 - Saturday,True,42,42,42,42
12,7 - Sunday,False,75,75,0,75
13,7 - Sunday,True,34,34,34,34

In [38]:
a_clicks_pivot = a_clicks_grouped\
   .pivot(index='day',
          columns='is_click',
          values='user_id')\
   .reset_index()
a_clicks_pivot

is_click            day  False  True
0            1 - Monday     70    43
1           2 - Tuesday     76    43
2         3 - Wednesday     86    38
3          4 - Thursday     69    47
4            5 - Friday     77    51
5          6 - Saturday     73    45
6            7 - Sunday     66    43

In [40]:
b_clicks_pivot = b_clicks_grouped\
   .pivot(index='day',
          columns='is_click',
          values='user_id')\
   .reset_index()
b_clicks_pivot

is_click            day  False  True
0            1 - Monday     81    32
1           2 - Tuesday     74    45
2         3 - Wednesday     89    35
3          4 - Thursday     87    29
4            5 - Friday     90    38
5          6 - Saturday     76    42
6            7 - Sunday     75    34

In [41]:
a_clicks_pivot['percent_clicked'] = a_clicks_pivot[True] / (a_clicks_pivot[True] + a_clicks_pivot[False])
a_clicks_pivot

is_click            day  False  True  percent_clicked
0            1 - Monday     70    43         0.380531
1           2 - Tuesday     76    43         0.361345
2         3 - Wednesday     86    38         0.306452
3          4 - Thursday     69    47         0.405172
4            5 - Friday     77    51         0.398438
5          6 - Saturday     73    45         0.381356
6            7 - Sunday     66    43         0.394495

In [42]:
b_clicks_pivot['percent_clicked'] = b_clicks_pivot[True] / (b_clicks_pivot[True] + b_clicks_pivot[False])
b_clicks_pivot

is_click            day  False  True  percent_clicked
0            1 - Monday     81    32         0.283186
1           2 - Tuesday     74    45         0.378151
2         3 - Wednesday     89    35         0.282258
3          4 - Thursday     87    29         0.250000
4            5 - Friday     90    38         0.296875
5          6 - Saturday     76    42         0.355932
6            7 - Sunday     75    34         0.311927

11.
Compare the results for A and B. What happened over the course of the week?

Do you recommend that your company use Ad A or Ad B?

Ad A is better